import dotenv from "dotenv";
dotenv.config();

const QUERY_LIMIT_ITEM = 20;
const TRENDING_REDUCING_LIMIT_ITEM = 10;

const DEVELOPMENT_URL = process.env.DEVELOPMENT_URL;
const PRODUCTION_URL = process.env.PRODUCTION_URL;

export {
	QUERY_LIMIT_ITEM,
	TRENDING_REDUCING_LIMIT_ITEM,
	DEVELOPMENT_URL,
	PRODUCTION_URL
};
